add intermedia span type and make it the default type
instana/instana-php-opentracing pull request #4
Opened 2020-09-25 11:27 UTC by steveww

The default span type should be intermediate
Added intermediate type to SpanType and made it the default when setting the span.kind.

Not sure if it should be the default when a span is created to be possibly overwritten later?

2020-09-25 16:28 UTC, gooh requested changes
Is there any particular reason why you are not using the `local` span type?
The additional intermediate type shouldn't be needed.

2020-09-28 08:10 UTC, steveww commented
The other tracers use `intermediate` as the span type.
I do not know if PHP is using `local` for something else.

2020-09-29 09:14 UTC, mmanciop commented
IMO we need to deprecate `localType` and use `intermediateType()` as the new default.

2020-10-06 09:53 UTC, closed without merging

2020-10-06 10:02 UTC, gooh commented
https://github.com/instana/instana-php-opentracing/issues/8